### ISSUE TITLE
add extensions file

### ISSUE THREAD

**Issue by willfarrell** [gordonfn/mackenzie-db-schema#3]
## User Story
As a [user description]
I want [desired action]
So that [desired outcome]

## Acceptance Criteria
- [ ] Given [context] and when [event] then [outcome]
- [ ] Given [context] and when [event] then [outcome]
- [ ] Given [context] and when [event] then [outcome]

## Notes
- postgis w/ update
```sql
CREATE EXTENSION pg_trgm;
```
---
_Tesera Standard Issue Template_

**Comment by Scobel** [comment]
Part of 3.1 Deploy
